# Generated by Django 3.1.2 on 2020-10-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=2)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('cases', models.CharField(max_length=10)),
                ('deaths', models.CharField(max_length=10)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
    ]
